#cloud-config
users:
  - name: app
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGCa/WtJnq8vYdxMVZg/LrSEsyrn2uzdWiM/PWNcry0yExyqFw5b27eNEizEDPuBgd50DmQOYDmAh+V6RiQcZPLwZT74HWurZuDRTN1DaHyddGIL8XRNVOHAzOXaK0yG9rRjEwscdzVnvsOdBJWYzW7ZH81DPQQ/vqDcy7A9hiSBltxpANPRUVx639uTMtRhHQQYtdAb8z4bQKOItT+paemyGoIlj0siSS9Xph3ob76BMwMNIao78XsS3LHFU4mgoFFmokrd95BdPfSN3L+QzNV6qfSrnm1reyVywe5tjr6cpTKffqk24eVJDx8tNmXk2OK/nDZKSdmvQ33GKiAsotSqi3M7DjT+zQnsMrh0xY1JxKuixa0MrQv5VSg009e2RGHpcGDHzfUb2lLGXX5kMf3Z788LOhdwYXVXI5LEaGsldvGiIDz2koiJAe3A0P3p0Z+rk1BKh1DEJTK48gn3Tz7OIuF81zLfTMrkXdBz+15dPDrciAfj9nKAQ32YJ3u/0= larrybotha@Larry MacBook
    # allow user to use sudo without password
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    # give the user sudo privileges
    groups: sudo
    # use bash as the default shell
    shell: /bin/bash

runcmd:
  # make the SSH daemon listen on port 4444
  - sed -i -e '/^Port/s/^.*$/Port 4444/' /etc/ssh/sshd_config
  # disable root login
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  # allow the `app` user to log in
  - sed -i -e '$aAllowUsers app' /etc/ssh/sshd_config
  # restart the SSH service
  - restart ssh
